spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jwt
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  security:
    jwt:
      secret-key: ea8ee9c180656e781b93cf377a6c98224650e391a7914ef35b3b36e0b82ca9c7
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000
